### ISSUE TITLE
Seems to try and invoke sh on windows

### ISSUE THREAD

**Issue by pwr22** [brentp/gargs#10]
Should this be running `cmd /C` instead?

```
C:\Users\rpeter>gargs --version
gargs 0.3.9
```

```
C:\Users\rpeter>echo 1 | gargs "echo {}"
[41;1mERROR with command: Command('echo 1 ', , [no stdout], exit-code: 1, error: exec: "sh": executable file not found in %PATH%, run-time: 14.0192ms)[0m
```

**Comment by brentp** [comment]
I should remove the windows binary. I don't know enough about windows to support it.

**Comment by pwr22** [comment]
Sure, fair enough. Thanks for getting back to me quickly!

**Comment by brentp** [comment]
sure thing. I removed the windows binary from the latest release. I'd be glad to accept a PR that ensured windows support. It may even work by setting `SHELL=cmd` or whatever but I don't have a setup to test.

**Comment by pwr22** [comment]
> It may even work by setting `SHELL=cmd`

Tried that and it didn't work.

So I changed the code enough to get it working on windows then hit the same issue I see in https://github.com/shenwei356/rush/issues/17

In the default case `-p 1` things seem to work alright as far as I can tell. Would you be interested as that in a PR?

**Comment by brentp** [comment]
if it can work with p > 1, then yes.

**Comment by pwr22** [comment]
It will work but it will leave the other processes hanging around after `gargs -e` exits after the first failure. When this gets fixed in `rush` I'll see about backporting that. Windows doesn't even have `xargs` available by default so there more of these nice tools we can get working there the better 😄
