### ISSUE TITLE
option --time-out is needed.

### ISSUE THREAD

**Issue by shenwei356** [brentp/gargs#5]
Hi Brent,

Thanks for share this cool tool, which is better than parallel for commands with nested quotation.

If find that, in some cases, e.g., downloading a web page using some tool, the process may hang and never end. This  will not return finish or fail signal, a timeout mechanism could help.

Merry Christmas and Happy New Year!
Wei

**Comment by brentp** [comment]
I agree. I will have a look at this as I have time and I welcome pull-requests. Could be done with a context.

**Comment by shenwei356** [comment]
I'll read the code and try to add this feature.

**Comment by brentp** [comment]
I suspect the code is not readily amenable to this change due to my short-sightedness, but it's doable, I'm sure.

**Comment by shenwei356** [comment]
I can't follow your code, maybe I can reinvent this wheel :( :joy:

**Comment by brentp** [comment]
why don't you look at replacing `exec.Command` with `exec.CommandContext`? https://golang.org/pkg/os/exec/#CommandContext

**Comment by shenwei356** [comment]
Sound easy, can you please replace it when you free? I try to digest all the code, but it needs more time. And I want to invent a new wheel :)

**Comment by shenwei356** [comment]
Dear @brentp , I made a similar tool [rush](https://github.com/shenwei356/rush) borrowed some idea of gargs and GNU parallel, which has similar [performance](https://github.com/shenwei356/rush/releases as gargs).

During the development, I finally understood your code :smile: .

The first version [v0.0.1](https://github.com/shenwei356/rush/releases/tag/v0.0.1) is out, could you please try and give some advices?
